spring.application.name: Table_Turn

server:
  port: 24001

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:23001:orcl
    driver-class-name: oracle.jdbc.OracleDriver
    username: TABLE_USER
    password: TABLE_USER