spring.application.name: Table_Turn

server:
  port: 80
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:oracle:thin:@222.112.211.95:1521:orcl
    driver-class-name: oracle.jdbc.OracleDriver
    username: TABLE_USER
    password: TABLE_USER
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  mapper-locations: mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true